title: Vega_Expository
email: 24110314@iitgn.ac.in
description: "Vega is a visualization grammar, a declarative language for creating, saving, and sharing interactive
 visualization designs. With Vega, you can describe the visual appearance and interactive behavior of a visualization in JSON format.
  This allows you to create reusable visualization components and easily reproduce visualizations across different platforms."

baseurl: "" # Leave empty for GitHub Pages
url: "https://yourusername.github.io"
permalink: pretty

twitter_username: jekyllrb
github_username: jekyll

# Theme and Plugins
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude files from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
